<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>br.inf.ufg.mddsm</groupId>
		<artifactId>mddsm</artifactId>
		<version>1.0-SNAPSHOT</version>
	</parent>
	<artifactId>mgridvm</artifactId>
	<name>mgridvm</name>
	<dependencies>
		<dependency>
			<groupId>br.inf.ufg.mddsm</groupId>
			<artifactId>mddsm-broker-model</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>br.inf.ufg.mddsm</groupId>
			<artifactId>mddsm-broker</artifactId>
			<version>1.0-SNAPSHOT</version>
		</dependency>
		<dependency>
			<groupId>com.googlecode.clichemaven</groupId>
			<artifactId>cliche</artifactId>
			<version>110413</version>
		</dependency>
	</dependencies>

	<repositories>
		<repository>
			<id>jcenter</id>
			<url>https://jcenter.bintray.com/</url>
		</repository>
	</repositories>
</project>
