<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="base" nsURI="http://www.inf.ufg.br/mestrado/sb/base" nsPrefix="sb.base">
  <eClassifiers xsi:type="ecore:EClass" name="Manager" eSuperTypes="#//metadata/Annotable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iface" lowerBound="1" eType="#//common/Interface"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actions" upperBound="-1"
        eType="#//common/Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//Handler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateManager" eType="#//StateManager"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceManager" eType="#//ResourceManager"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autonomicManager" eType="#//AutonomicManager"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policyManager" lowerBound="1"
        eType="#//PolicyManager" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceManager" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="iface" lowerBound="1" eType="#//common/Interface"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stateTypes" upperBound="-1"
        eType="#//context/State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutonomicManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="identifies" upperBound="-1"
        eType="#//autonomic/Symptom" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requests" upperBound="-1"
        eType="#//autonomic/ChangeRequest" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="plans" upperBound="-1"
        eType="#//autonomic/ChangePlan" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PolicyManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="points" upperBound="-1"
        eType="#//policy/PolicyEvaluationPoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="handlers" upperBound="-1"
        eType="#//policy/PolicyEvaluationHandler" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="policies" upperBound="-1"
        eType="#//policy/Policy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Handler">
    <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
        eType="#//common/Signal"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        eType="#//common/ActionExecution" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstanceResourceManager" eSuperTypes="#//ResourceManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="instances" upperBound="-1"
        eType="#//Instance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Instance" eSuperTypes="#//metadata/Annotable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impl" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="iface" lowerBound="1" eType="#//common/Interface"
        derived="true"/>
  </eClassifiers>
  <eSubpackages name="context" nsURI="http://www.inf.ufg.br/mestrado/sb/base/context"
      nsPrefix="sb.base.context">
    <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//common/Bindable">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
          eType="#//context/State" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
          eType="#//context/Property" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//context/Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Property">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="metadata" nsURI="http://www.inf.ufg.br/mestrado/sb/base/metadata"
      nsPrefix="sb.base.metadata">
    <eClassifiers xsi:type="ecore:EClass" name="Feature">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="attributes" upperBound="-1"
          eType="#//metadata/Attribute" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="subFeatures" upperBound="-1"
          eType="#//metadata/Feature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Annotable" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="features" ordered="false"
          upperBound="-1" eType="#//metadata/Feature" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Attribute">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="autonomic" nsURI="http://www.inf.ufg.br/mestrado/sb/base/autonomic"
      nsPrefix="sb.base.autonomic">
    <eClassifiers xsi:type="ecore:EClass" name="Symptom">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" lowerBound="1"
          upperBound="-1" eType="#//common/Binding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="conditions" lowerBound="1"
          upperBound="-1" eType="#//common/Condition" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangeRequest">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" lowerBound="1"
          eType="#//autonomic/Symptom"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ChangePlan">
      <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" lowerBound="1"
          eType="#//autonomic/ChangeRequest"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
          eType="#//common/ActionExecution" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="policy" nsURI="http://www.inf.ufg.br/mestrado/sb/base/policy"
      nsPrefix="sb.base.policy">
    <eClassifiers xsi:type="ecore:EClass" name="PolicyEvaluationPoint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signal" lowerBound="1"
          eType="#//common/Signal"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="request" lowerBound="1"
          eType="#//policy/PolicyEvaluationRequest" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyEvaluationRequest">
      <eStructuralFeatures xsi:type="ecore:EReference" name="handler" lowerBound="1"
          eType="#//policy/PolicyEvaluationHandler"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//common/ParameterBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyEvaluationHandler">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//common/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="handlerImpl" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="evaluation" lowerBound="1"
          eType="#//policy/PolicyEvaluation" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyEvaluationContext">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//common/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyEvaluation">
      <eStructuralFeatures xsi:type="ecore:EReference" name="feature" lowerBound="1"
          eType="#//common/Value" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="contextBinding" upperBound="-1"
          eType="#//common/ParameterBinding" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="context" lowerBound="1"
          eType="#//policy/PolicyEvaluationContext" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Policy">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="businessValue" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="decision" lowerBound="1"
          eType="#//policy/PolicyDecision" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PolicyDecision">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameter" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="common" nsURI="http://www.inf.ufg.br/mestrado/sb/base/common"
      nsPrefix="sb.base.common">
    <eClassifiers xsi:type="ecore:EClass" name="Parameter">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signal" abstract="true" eSuperTypes="#//common/Bindable">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//common/Parameter" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Event" eSuperTypes="#//common/Signal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Call" eSuperTypes="#//common/Signal"/>
    <eClassifiers xsi:type="ecore:EClass" name="Interface">
      <eStructuralFeatures xsi:type="ecore:EReference" name="provides" upperBound="-1"
          eType="#//common/Call" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="signals" upperBound="-1"
          eType="#//common/Event" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Value" abstract="true"/>
    <eClassifiers xsi:type="ecore:EClass" name="SignalSource" eSuperTypes="#//common/Value"/>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterValue" eSuperTypes="#//common/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//common/Parameter"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExpressionValue" eSuperTypes="#//common/Value">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
          eType="#//common/Parameter" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SequenceAction" eSuperTypes="#//common/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="children" lowerBound="1"
          upperBound="-1" eType="#//common/ActionExecution" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnqueueCall" eSuperTypes="#//common/Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="call" lowerBound="1"
          eType="#//common/Call"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//common/ParameterBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MacroAction" eSuperTypes="#//common/Action">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="impl" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionExecution" eSuperTypes="#//common/Value">
      <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
          eType="#//common/Action"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindings" upperBound="-1"
          eType="#//common/ParameterBinding" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ParameterBinding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
          eType="#//common/Parameter"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1"
          eType="#//common/Value" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Condition">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Binding">
      <eStructuralFeatures xsi:type="ecore:EReference" name="bindable" lowerBound="1"
          eType="#//common/Bindable"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Bindable" abstract="true" interface="true"/>
  </eSubpackages>
</ecore:EPackage>
