<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="metalang4md" nsURI="http://www.inf.ufg.br/metalang4md" nsPrefix="metalang4md">
  <eClassifiers xsi:type="ecore:EClass" name="EActor" eSuperTypes="#//EDomainSpecificElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="EItem" eSuperTypes="#//EDomainSpecificElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arisingBehavior" eType="#//EArising"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ECardinality">
    <eLiterals name="ONE"/>
    <eLiterals name="MANY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EInteractionBehavior">
    <eLiterals name="SYNC"/>
    <eLiterals name="ASYNC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDomainSpecificType" eSuperTypes="#//EDomainSpecificElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="#//ECardinality"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interactionBehavior" eType="#//EInteractionBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindInteraction" eType="#//ECoordinationBehavior"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="binding" upperBound="-1"
        eType="#//EDomainSpecificType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EDomainSpecificElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="commandPriority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="EArising">
    <eLiterals name="STATIC"/>
    <eLiterals name="DYNAMIC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ECoordinationBehavior">
    <eLiterals name="LOCAL"/>
    <eLiterals name="DISTRIBUTED" value="1"/>
  </eClassifiers>
</ecore:EPackage>
