<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cml" nsURI="http://www.inf.ufg.br/metalang4md/cml" nsPrefix="cml">
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationSchema"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataSchema" eSuperTypes="#//CommunicationSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="request" eType="#//Request"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataContent" eType="#//DataContent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediaRequest" eSuperTypes="#//Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestAction" eType="#//ActionTypeRequest"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormRequest" eSuperTypes="#//Request">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataContent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Medium" eSuperTypes="#//DataContent ../metalang4md.ecore#//EItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumDataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validityPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firstTransferTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voiceCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form" eSuperTypes="#//DataContent ../metalang4md.ecore#//EItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subForm" upperBound="-1"
        eType="#//Form" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subMedium" lowerBound="1"
        upperBound="-1" eType="#//Medium" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formDataType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suggestedApp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voiceCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="#//ActionTypeForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSpec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BuiltInType">
    <eLiterals name="TEXT_FILE"/>
    <eLiterals name="LIVE_AUDIO" value="1"/>
    <eLiterals name="LIVE_VIDEO" value="2"/>
    <eLiterals name="LIVE_AV" value="3"/>
    <eLiterals name="TEXT" value="4"/>
    <eLiterals name="AUDIO_FILE" value="5"/>
    <eLiterals name="VIDEO_FILE" value="6"/>
    <eLiterals name="AV_FILE" value="7"/>
    <eLiterals name="NON_STREAM_FILE" value="8"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionTypeRequest">
    <eLiterals name="OPEN"/>
    <eLiterals name="SAVE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActionTypeForm">
    <eLiterals name="SEND"/>
    <eLiterals name="SEND_ON_DEMAND" value="1"/>
    <eLiterals name="SECURE_SEND" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ControlSchema" eSuperTypes="#//CommunicationSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="attachedParty" lowerBound="1"
        upperBound="-1" eType="#//AttachedParty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataType" lowerBound="1"
        upperBound="-1" eType="#//DataType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="communicationID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceCaps" lowerBound="1"
        upperBound="-1" eType="#//DeviceCapability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isVirtual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isLocal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataTypeRef" lowerBound="1"
        upperBound="-1" eType="#//DataTypeRef" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        upperBound="-1" eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttachedParty" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isAttached" lowerBound="1"
        eType="#//IsAttached" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="person" lowerBound="1"
        eType="#//Person" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataType" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType"/>
  <eClassifiers xsi:type="ecore:EClass" name="FormType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subFormType" upperBound="-1"
        eType="#//FormType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subMediumType" upperBound="-1"
        eType="#//MediumType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="actionTF" eType="#//ActionTypeForm"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suggestedApp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voiceCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutSpec" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediumType" eSuperTypes="#//DataType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastModifiedTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="validityPeriod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileTransferTime" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="voiceCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="derivedFromBuiltInType"
        eType="#//BuiltInType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Person">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personRole" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsAttached">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="personID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceCapability">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capability" eType="#//BuiltInType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FormTypeRef" eSuperTypes="#//DataTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="formTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MediumTypeRef" eSuperTypes="#//DataTypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediumTypeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
