<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="mgridml" nsURI="http://www.inf.ufg.br/metalang4md/mgridml" nsPrefix="mgridml">
  <eClassifiers xsi:type="ecore:EClass" name="MGridSchema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mgridModelID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGridControlSchema" eSuperTypes="#//MGridSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mcgrid" lowerBound="1"
        eType="#//MCGrid" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGridDataSchema" eSuperTypes="#//MGridSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mdGrid" upperBound="-1"
        eType="#//MDGrid" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MCGrid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mgcontroller" lowerBound="1"
        upperBound="-1" eType="#//MGController" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mcgridID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MDGrid">
    <eStructuralFeatures xsi:type="ecore:EReference" name="plantElem" upperBound="-1"
        eType="#//PlantElem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdgridID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mdgrid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PlantElem" eSuperTypes="../metalang4md.ecore#//EItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platE_ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="#//PlantElem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceProperty" upperBound="-1"
        eType="#//DeviceProperty" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deviceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wattage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operational" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadDevice" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="control" eType="#//ControlEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="critical" eType="#//CriticalEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageDevice" eSuperTypes="#//Device">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="charging" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="chargeT" eType="#//ChargeEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceProperty">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Source" eSuperTypes="#//PlantElem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="wattage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="onDemand" eType="#//ControlEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operational" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartMeter" eSuperTypes="#//Meter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tariff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operational" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Meter" eSuperTypes="#//PlantElem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyMeter" eSuperTypes="#//Meter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operational" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGController" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ctypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AtomicController" eSuperTypes="#//MGController">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controllerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinality" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MGridController" eSuperTypes="#//MGController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="mgcontroller" upperBound="-1"
        eType="#//MGController" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mgridControllerID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalLoads" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="totalSources" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadController" eSuperTypes="#//AtomicController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadDeviceType" lowerBound="1"
        upperBound="-1" eType="#//LoadDeviceType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lcProperty" upperBound="-1"
        eType="#//LC_Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageController" eSuperTypes="#//AtomicController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="storageDeviceType" lowerBound="1"
        upperBound="-1" eType="#//StorageDeviceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceController" eSuperTypes="#//AtomicController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceType" lowerBound="1"
        upperBound="-1" eType="#//SourceType" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PCC" eSuperTypes="#//AtomicController">
    <eStructuralFeatures xsi:type="ecore:EReference" name="meterType" lowerBound="1"
        eType="#//MeterType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connected" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MeterType" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceType" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageDeviceType" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerThres" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="upperThres" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoadDeviceType" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="soTypeID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="critical" eType="#//CriticalEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="usage" eType="#//UsageEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LC_Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SmartMType" eSuperTypes="#//MeterType"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegacyMType" eSuperTypes="#//MeterType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="CriticalEnum">
    <eLiterals name="SENSITIVE"/>
    <eLiterals name="ADJUSTABLE" value="1"/>
    <eLiterals name="SHEDABLE" value="2"/>
    <eLiterals name="ANY" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceEnum">
    <eLiterals name="AC"/>
    <eLiterals name="DC" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ControlEnum">
    <eLiterals name="CONTROLLABLE"/>
    <eLiterals name="NON_CONTROLLABLE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChargeEnum">
    <eLiterals name="CHARGE"/>
    <eLiterals name="NEUTRAL" value="1"/>
    <eLiterals name="DISCHARGE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UsageEnum">
    <eLiterals name="HVAC"/>
    <eLiterals name="LIGHTING" value="1"/>
    <eLiterals name="SMALL_APPLS" value="2"/>
    <eLiterals name="LARGER_APPLS" value="3"/>
  </eClassifiers>
</ecore:EPackage>
