<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rbcml" nsURI="http://www.inf.ufg.br/metalang4md/rbcml" nsPrefix="rbcml">
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" upperBound="-1"
        eType="#//User" eOpposite="#//User/role"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleconnection" lowerBound="1"
        upperBound="-1" eType="#//RoleConnection" eOpposite="#//RoleConnection/role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoleConnection" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cardinalityMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EShort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendCap" upperBound="4"
        eType="#//MediaType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recvCap" upperBound="4"
        eType="#//MediaType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        eOpposite="#//Role/roleconnection"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connection" lowerBound="1"
        eType="#//Connection" eOpposite="#//Connection/roleconnection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connection" eSuperTypes="../metalang4md.ecore#//EActor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamAudio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="streamVideo" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="form" upperBound="2" eType="#//Form"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleconnection" lowerBound="1"
        upperBound="-1" eType="#//RoleConnection" eOpposite="#//RoleConnection/connection"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Form">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeData" eType="#//PrimitiveType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="../metalang4md.ecore#//EItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" lowerBound="1"
        eType="#//Device" eOpposite="#//Device/user"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="role" lowerBound="1" eType="#//Role"
        eOpposite="#//Role/user"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Device" eSuperTypes="../metalang4md.ecore#//EDomainSpecificType">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" lowerBound="1" eType="#//User"
        eOpposite="#//User/device"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PrimitiveType">
    <eLiterals name="STRING_TYPE"/>
    <eLiterals name="BLOB_TYPE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MediaType">
    <eLiterals name="VIDEO"/>
    <eLiterals name="AUDIO" value="1"/>
    <eLiterals name="STRING" value="2"/>
    <eLiterals name="BLOB" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Communication">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
        eType="#//Connection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roles" upperBound="-1"
        eType="#//Role" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roleconnection" upperBound="-1"
        eType="#//RoleConnection" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="device" upperBound="-1"
        eType="#//Device" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="user" upperBound="-1" eType="#//User"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
