<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="adapter-v1" nsURI="http://www.inf.ufg.br/broker/adapter-v1"
    nsPrefix="adapter-v1">
  <eClassifiers xsi:type="ecore:EClass" name="Adapter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="domain" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mapper" eType="#//Mapper"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dispatcher" upperBound="-1"
        eType="#//Dispatcher" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="domainElements" eType="#//domain/DomainElements"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="platformElements" eType="#//platform/PlatformElements"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapper">
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentsRelated" upperBound="-1"
        eType="#//Components" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Parameter" derived="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="body" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dispatcher">
    <eStructuralFeatures xsi:type="ecore:EReference" name="comm" upperBound="-1" eType="#//platform/PSComm"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" upperBound="-1" eType="#//platform/PSCmd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="function" eType="#//Function"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Components">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" lowerBound="1"
        eType="#//platform/PSResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" lowerBound="1"
        eType="#//domain/DSEntity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commands" upperBound="-1"
        eType="#//CommandRelation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value2" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandRelation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capability" lowerBound="1"
        eType="ecore:EClass http://www.inf.ufg.br/broker/psk#//Capability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" lowerBound="1" eType="ecore:EClass dsk.ecore#//EDSC"/>
  </eClassifiers>
  <eSubpackages name="platform" nsURI="http://www.inf.ufg.br/broker/adapter/platform"
      nsPrefix="platform">
    <eClassifiers xsi:type="ecore:EClass" name="PlatformElements">
      <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
          eType="#//platform/PSResource" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comm" upperBound="-1"
          eType="#//platform/PSComm" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="cmd" upperBound="-1"
          eType="#//platform/PSCmd" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="comp" upperBound="-1"
          eType="#//platform/PSComponent" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="caps" upperBound="-1"
          eType="#//platform/Capability" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PSComm" eSuperTypes="psk.ecore#//Communication"/>
    <eClassifiers xsi:type="ecore:EClass" name="PSCmd" eSuperTypes="psk.ecore#//Command"/>
    <eClassifiers xsi:type="ecore:EClass" name="PSResource" eSuperTypes="psk.ecore#//PSResource"/>
    <eClassifiers xsi:type="ecore:EClass" name="PSComponent" eSuperTypes="psk.ecore#//Component"/>
    <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="http://www.inf.ufg.br/broker/psk#//Capability"/>
  </eSubpackages>
  <eSubpackages name="domain" nsURI="http://www.inf.ufg.br/broker/adapter/domain"
      nsPrefix="domain">
    <eClassifiers xsi:type="ecore:EClass" name="DSEntity" eSuperTypes="dsk.ecore#//EDSEntity"/>
    <eClassifiers xsi:type="ecore:EClass" name="DomainElements">
      <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
          eType="#//domain/DSEntity" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="dscs" upperBound="-1"
          eType="#//domain/DSC" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DSC" eSuperTypes="dsk.ecore#//EDSC"/>
  </eSubpackages>
</ecore:EPackage>
