<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="af"
    nsURI="http://www.inf.ufg.br/mestrado/sb/af" nsPrefix="sb.af">
  <eClassifiers xsi:type="ecore:EClass" name="TouchpointManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="touchpoint" lowerBound="1"
        eType="#//touchpoint/Touchpoint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resourceManager" lowerBound="1"
        eType="ecore:EClass base.ecore#//ResourceManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="symptoms" upperBound="-1"
        eType="#//Symptom" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Symptom">
    <eStructuralFeatures xsi:type="ecore:EReference" name="call" lowerBound="1" eType="ecore:EClass base.ecore#//ActionCall"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="expected" lowerBound="1"
        eType="ecore:EClass base.ecore#//Value" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Plan">
    <eStructuralFeatures xsi:type="ecore:EReference" name="symptom" lowerBound="1"
        eType="#//Symptom" containment="true"/>
  </eClassifiers>
  <eSubpackages name="touchpoint" nsURI="http://www.inf.ufg.br/mestrado/sb/af/touchpoint"
      nsPrefix="sb.af.touchpoint">
    <eClassifiers xsi:type="ecore:EClass" name="Touchpoint">
      <eStructuralFeatures xsi:type="ecore:EReference" name="sensors" upperBound="-1"
          eType="#//touchpoint/Sensor" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="effectors" upperBound="-1"
          eType="#//touchpoint/Effector" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Sensor" eSuperTypes="base.ecore#//Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="Effector" eSuperTypes="base.ecore#//Action"/>
  </eSubpackages>
</ecore:EPackage>
