<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="psk" nsURI="http://www.inf.ufg.br/broker/psk" nsPrefix="psk">
  <eClassifiers xsi:type="ecore:EClass" name="Psk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="platform" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="components" lowerBound="1"
        upperBound="-1" eType="#//Component" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//ResourceKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comm" lowerBound="1" upperBound="-1"
        eType="#//CommunicationProtocols" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationProtocols">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="api" eType="#//CommAPIEnum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataSupported" eType="#//DataFormatEnum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" lowerBound="1"
        upperBound="-1" eType="#//Parameter" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arrange" eType="#//ArrangementENum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composition" eType="#//CompositionEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primitiveResource" upperBound="-1"
        eType="#//ResourceKind" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capabilities" lowerBound="1"
        upperBound="-1" eType="#//CapabilityKind" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="address" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="comm" lowerBound="1" upperBound="-1"
        eType="#//CommunicationProtocols" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityKind">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="function" eType="#//CapabilityType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attribute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="composed" upperBound="-1"
        eType="#//Parameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CommAPIEnum">
    <eLiterals name="REST"/>
    <eLiterals name="GRAPHQL" value="1"/>
    <eLiterals name="GRPC" value="2"/>
    <eLiterals name="WEBHOOKS" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataFormatEnum">
    <eLiterals name="JSON"/>
    <eLiterals name="XML" value="1"/>
    <eLiterals name="TXT" value="2"/>
    <eLiterals name="XDR" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArrangementENum">
    <eLiterals name="PHISICAL"/>
    <eLiterals name="LOGICAL" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompositionEnum">
    <eLiterals name="SINGLE"/>
    <eLiterals name="COMPOSITE" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CapabilityType">
    <eLiterals name="SENSOR"/>
    <eLiterals name="ACTUATOR"/>
  </eClassifiers>
</ecore:EPackage>
